---
title: "Probability distributions"
output: html_document
---

# Wed Sept 16 - Samples, poulations, and probability distributions

## Samples and populations {#variables}

Populations are _all possible_ units and their associated observations of interest. Samples are a collection of observations from a population. The number of units in the sample is the sample size.

Variables, or measured quantities, are the characteristics that we record. Variables can be continuous, taking any value within a range, i.e., weight. Discrete variables can be ordered along the continuous scale (e.g., counts), and in some cases there are so many possibility that discrete variables can be treated essentially as continuous. For example, hypotheses that involve count data, when the values are large, are often tested with the same statistical tests as continuous data.

(Based on 2.1 of Quinn and Keough)

## Probability and probability distributions
Probabilities satisfy Kolmogorov's properties. Probabilities can be interpretted as the relative frequency of an event, or the 'degree of belief' an event will occur. 

Bayes' theorem relates to conditional probability $P(A|B)$, which is the probability an event $A$ will occur given and event $B$. Bayes' theorem is fundamental to Bayesian statistics.

The definition of independence is that that the probability of events $A$ and $B$ occurring can be calculated by multiplying their probabilities: $P(A,B) = P(A)P(B)$. We may not be justified in using that formula if $A$ and $B$ are not independent. We we say that our statistical method assumes that our residuals are independent, we mean that we can multiply the probabilities associated with each residual to calculate the probability of observing these residuals for all the data, i.e., $P(\epsilon_1, \dots, \epsilon_n) = \prod_{i=1}^n P(\epsilon_i)$. We will specifically show that we are using this assumption when we take the maximum likelihood approach to deriving the residual sum of squares formula (in a future lecture).

### Probability distributions for variables

The normal or Gaussian distribution,

\[f(y) = \frac{1}{\sqrt{2\pi\sigma^2}}e^{-(y-\mu)^2/2\sigma^2}. \]

The standard normal distribution has a mean, $\mu = 0$, and variance, $\sigma^2 = 1$. Notational we might write the standard normal distribution as $N(0,1)$ where $N(\mu,\sigma)$ is the normal distribution with a mean of $\mu$ and variance of $\sigma^2$.

The Bionomial distribution

\[P(y=r) = \frac{n!}{r!(n-r)!}p^r(1-p)^{p-r}  \]

### Probability distributions for statistics

See Figure 2.1 in Q&K (or do an internet search) to see the graphs of these distributions: $z$ (standard normal); Student's $t$ (ratio of the difference between the sample statistic and its population value to the sample standard deviation); $\chi^2$ (square of values from a standard normal distribution; used for interval estimation of variances); and $F$ (ratio of two independent $\chi^2$ variables, each divided by its degrees of freedom (df); used for comparing variances).

(Based on 2.2 of Quinn and Keough. See also  - [Ch6.2: Probability distributions - notation](https://davidcschneider.github.io/StatisticalScience/LNotes/Pt2/Ch6_2.pdf))

## Empirical frequency distributions

(see also [Ch6.1: Empirical frequency distributions](https://davidcschneider.github.io/StatisticalScience/LNotes/Pt2/Ch6_1.pdf))

## Comparing observations to probability distributions (Ch6.3)

 (based on [Ch6.3: Comparing observed distributions to probability models](https://davidcschneider.github.io/StatisticalScience/LNotes/Pt2/Ch6_3.pdf))




