---
title: "Hypothesis testing"
output: html_document
---

# Mon Sept 21 - Review Quiz 1, statistical 

Frequentist estimation and hypothesis testing will be moved to the future lectures.

## Review Quiz 1
Available on Brightspace.

## Probability distributions (continued)

### Probability distributions for statistics

See Figure 2.1 in Quinn and Kenough (or do an internet search) to see the graphs of these distributions:

- $z$ (standard normal). Quantiles for a standard normal distribution. Used for confidence intervals.

- Student's $t$. Describes the ratio of the difference between the sample statistic and its population value to the sample standard deviation. 

- $\chi^2$. Describes the square of values from a standard normal distribution. Used for interval estimation of variances.

- $F$. Describes the ratio of two independent $\chi^2$ variables, each divided by its degrees of freedom (df). Used for comparing variances.

(Based on 2.2 of Quinn and Keough. See also  - [Ch6.2: Probability distributions - notation](https://davidcschneider.github.io/StatisticalScience/LNotes/Pt2/Ch6_2.pdf))

## Empirical frequency distributions

See [Ch6.1: Empirical frequency distributions](https://davidcschneider.github.io/StatisticalScience/LNotes/Pt2/Ch6_1.pdf)



<!-- ## Readings -->

<!-- - Ch 2.5 Quinn and Keough -->

<!-- - Ch7.2, 7.3 -->
