---
title: "Exploratory data analysis"
output: html_document
---

# Wed Oct 07 - Exploratory data analysis

Today's lecture material will not be on Exam I.

## Introduction to linear models (continued)

[Errors and residuals](https://en.wikipedia.org/wiki/Errors_and_residuals): Errors are the difference between the observation and the population value. Residuals are the difference between the observation and the estimated value.

### Assumptions for linear model inference

- OLS assumes independent identically distributed errors, and specifically, that the identical distributions are normal distributions with a mean of 0 and constant variance, $\sigma^2$.

- Violations can result in inaccurate confidence intervals and p-values, although OLS is reasonably robust, at lest to non-normality and unequal variance.

Assumptions of:

- **Zero conditional means of errors**. Check by plotting the residuals against the predictors.

- **Independence of errors**. The assumption strictly refers to independence of the model error terms, but it is often described as the independence of the observations, because correlated/non-independent observations usually result in non-independent errors. Test with a plot of the residuals against the predictors and look for obvious positive, negative, or cyclical trends. If spatial autocorrelation is the concern, make a variogram (Dale and Fortin 2009).

- **Homogeneity of error variances (homoskedasticity).** Heteroskedasticity (non-equal variances) often results when the underlying model error distribution is non-normal. Can also be due to outliers. Plot residuals against the predictor values, and look for unequal spread of the residuals. For categorical variables plot the residuals against the group means.

- **Normality of errors.** Assumption is that errors are normally distributed, but usually this means that response variables are normally distributed. Normality assumptions can be assessed with Q-Q plot (compares the quantiles of the data to the quantiles of a normal distribution), but statistical inference is generally robust to violations of the assumption of normally distributed errors and many statisticians do not view this assumption as a critical issue (Gelman and Hill 2006, cited on p57 of Quinn and Keough).

### Types of linear model (General and generalized)
These are the most common types of linear models used by biologists.l

**General linear models** are also commonly just called linear models. The response variable is continuous and has an underlying normal distribution. Use the identity link function.

**Continuous predictor variables: Regression**. This analysis is known as a regression, and the equation for the fitted regression is:

\[
\hat{y}_i = b_0 + b_1x_i
\]

where $\hat{y}_i$ are the fitted (or model-predicted) response variable values (i.e., as you did in assignment 2) and $b_0$ and $b_1$ are the fitted (or estimated) intercept and slope. If $b_1$ is not different from 0 then this predictor variable, $x_i$ explains very little of the variation that was measured in the response variable.

**Categorical predictor variables: ANOVA**. This analysis is known as ANOVA. As the preditor variables are discrete we might plot our data as boxplots (or violin plots etc). The equation for an ANOVA is:

\[
y_{ij} = \mu + \alpha_i + \epsilon_ij
\]

where $i$ is category $i$ and $j$ is a particular observation. The effect of category $i$ is measured as $\alpha_i$, which is written as being additive with respect to the mean $\mu$, which is calculated by taking the mean by considering the observations across all the categories (i.e. ignoring the categories). The term $\epsilon_{ij}$ represents error for the observation $i$ in category $j$.

The group (or category mean) is $\mu_i = \mu + \alpha_i$.

Software packages often implement and report ANOVA as:

\[
\hat{y}_{i} = b_0 + b_1 \mathbb{1}_{i=1} + \dots + b_{m-1} \mathbb{1}_{i=m-1} 
\]

which says that the estimated mean of category $i$ (the fitted parameter estimate) is $\hat{y}_i$ where $b_0$ is the estimated mean of the reference category (arbitrarily choosen and labelled $i=0$) and $i \in {0, 1, \dots, m-1}$ are estimates for the other $m-1$ categorical variable means (relative to the mean of the reference category).  $\mathbb{1}_{i=j}$ is an indicator variable that is 1 when we are considering catergory $i = j$ and 0 otherwise. This means that the formula to calculate the fitted value of $\hat{y}_i$ for a particular category is $b_0$ for the reference category or $\hat{y}_i=b_0 + b_j$ for any of the other categories. It does not matter which of the $m$ categorical variables are indexed by $0, 1$ or any of the other numbers up to $m-1$.

**Generalized linear models** include:

- Logistic regression: binary response; continuous predictor variables
- Possion regression: Poisson response; continuous predictor variables
- Contingency tables: Response is classified by two or more categorical variables. Question is about correlation or independence, i.e., 2 x 2 $\chi^2$ test for independence or deviation from an expected pattern.
- Linear mixed models. Predictor variables are modelled as fixed and random effects.

## Exploratory analysis

### Basic graphical tools

- Basic common graphs: histogram, dotplot, boxplot, probability plot (i.e., violin plot), scatterplot, scatterplot matrix

- Smoothing (i.e., LOESS or LOWESS)

- Residual plots

### Outliers

Quinn and Keough argue that outliers are best identified by exploratory analysis (i.e. box plots) rather than statistical tests. After identifying the outliers, first check it is not a mistake, i.e., an equipment malfunction or data entry error.

If you have an outlier, that does not have an explanation (in terms of being anomalous or a mistake), re-run the analysis without the outlier to determine if the outlier impacts the results. Cook's D-statistic measures how much an observation affects parameter estimation for linear models. You may need to use a statistic test developed for outliers.

You should only remove outliers from your data if you have an a priori reason to expect the outlire is an anomaly or a mistake.

### Am I fitting the right model?

**The underlying probability distribution**. Inference is often robust to violations of normality assumptions, but we should check for symmetry in response variables and residuals using boxplots and p-p plots.

If data is right-skewed, a log-trasformation could be considered, although inference is probably more robust if you instead consider errors following a Poisson distribution (i.e., a Poisson regression) or another distribution using ML estimation.

The common probability distributions have one peak. If your response variable is multi-peaked the best approach might be to split your analysis into multiple populations, with separate analysis for each population.

Data with many zeros is best split into two processes: no response; and given a response what is it's value. These statistical methods are called zero-inflated.

**Homogeneity of variances**. Often more important than the assumption of normal errors (or response variables) is the assumption that the normal distribution has constant variance. For the normal distribution, $\sigma^2$ is an estimated parameter for both OLS and ML. The Poisson distribution has the mean equal to the variance (such that the variance may not be constant), a reason for heteroskedasticity could be that a Poisson error distribution is more consistent with these data.

Quinn and Keough recommend graphical approaches to inspect for hetroskedasticity (non-homogeneity of variance), for example box plots. These are preferred to formal tests (although Levene's test is an option) unless testing for unequal variance is the focal research question.

**Is a linear model appropriate?** Examine this question by making a scatter plot. See also [Anscombe (1973)](https://www.sjsu.edu/faculty/gerstman/StatPrimer/anscombe1973.pdf).


### Is it Normal to transform data?

Transforming cm to m illustrates the arbitrary choices that we might make regarding transformations. The conclusions of linear transformations (i.e., cm to m) will be identical. 

Nonlinear transformations (i.e., taking the logarithm of the response variable) change the research question being addressed by the analysis. Such transformations might be made to meet distributional assumptions of linear model analysis. If you transform your response variable, it has been argued that you should present your results on the transformed scale (i.e., log-growth rather than growth).

Another common transformation is to take the squareroot of the response variable.

Transformations can also help satisfy linearity assumptions.

**Nowdays, it is not Normal to transform data**. It is generally awkward to frame research questions in terms of "log-growth" or the "square root of growth". Historically, transformations were needed because estimation with ML was computationally inaccessible. To meet distributional assumptions, it is better to use ML methods which have the flexibility to be formulated for a range of distributions.

### Standardizations

Standardizations can facilitate comparisons. Changing a variable to have a mean of 0 and a standard deviation of 1 is a common standardization.

### Missing data

There are different mechanisms for missingness. One approach to addressing missingness is imputation.

## Readings
- Ch 4.6-4.7 and Ch 5 Quinn and Keough
